mode: rule
mixed-port: 7890
allow-lan: true
log-level: info
secret: '9@&BKUMV&JyTuDA3'  # should be shuffled
external-controller: 0.0.0.0:9169
tun:
  stack: gVisor
  device: Meta
  auto-route: true
  strict-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  - tcp://any:53
  mtu: 9000
  enable: false
dns:
  enable: true
  prefer-h3: true
  nameserver:
    - "https://dns.google/dns-query#PROXY"
    - "https://security.cloudflare-dns.com/dns-query#PROXY"
    - "quic://dns.adguard-dns.com"
  proxy-server-nameserver:
    - "https://223.5.5.5/dns-query"
  nameserver-policy:
    "geosite:cn":
      - "https://223.5.5.5/dns-query#h3=true"
proxies:
proxy-groups:
rules:
  - GEOSITE,category-scholar-!cn,PROXY
  - GEOSITE,category-ads-all,REJECT
  - GEOSITE,youtube,PROXY
  - GEOSITE,google,PROXY
  - GEOSITE,cn,DIRECT
  - GEOSITE,private,DIRECT
  # - GEOSITE,tracker,DIRECT
  - GEOSITE,steam@cn,DIRECT
  - GEOSITE,category-games@cn,DIRECT
  - GEOSITE,geolocation-!cn,PROXY
  - GEOIP,private,DIRECT,no-resolve
  - GEOIP,telegram,PROXY
  - GEOIP,CN,DIRECT
  - DST-PORT,80/8080/443/8443,PROXY
  - MATCH,DIRECT
